trainer:
    max_epochs: 10
    check_val_every_n_epoch: 1
    callbacks:
        - class_path: pytorch_lightning.callbacks.ModelCheckpoint
          init_args:
              monitor: "test_loss"
              mode: "min"
              save_top_k: 1
              every_n_epochs: 10  # should be the same as `check_val_every_n_epoch`
              save_on_train_epoch_end: true
              verbose: true
              filename: "{epoch}-{test_loss:.4f}"
